name: build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  run:
    name: Build
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest    # build issues with `ar` (!!!)
          #- windows-latest   # certificate problem
        ocaml-compiler:
          - '4.08'
          - '4.14'
          - '5.3'
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ocaml/setup-ocaml@v3
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
    - run: opam pin -n .
    - run: opam depext -yt ezcurl ezcurl-lwt
    - run: opam install -t . --deps-only
    - run: opam exec -- dune build @install
    - run: opam exec -- dune runtest
